version: "3.9"
name: "road_vision_store"
services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=user
      - POSTGRES_DB=road_vision  
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks:
      db_network:

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:5050"
    networks:
      db_network:

  store:
    container_name: store
    build: ../service/store
    depends_on:
      - postgres
    restart: always
    environment:
      POSTGRES_CONNECTION_URL: postgresql://user:postgres_password@postgres/road_vision
    ports:
      - "3000:3000"
    networks:
      db_network:

networks:
  db_network:

volumes:
  postgres-data:
  pgadmin-data:

